version: "3.8"
services:
  postgres_db:
    container_name: "postgres_db"
    image: "postgres:16-alpine"
    env_file: ./.env
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT} # 5435:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # 123
      POSTGRES_DB: ${POSTGRES_DB} # bookstore
    volumes:
      - postgres-data:${DB_VOLUME_URL}

volumes:
  postgres-data:

